#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5517-web
    bind *:80
    mode http
    balance roundrobin
    server 5479-web-01 3.87.98.29:80 check
    server 5479-web-02 54.146.204.211:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart